name: Build macOS Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4 # Updated to latest
      - name: Set up Python
        uses: actions/setup-python@v4 # Already uses v4, compatible with Node.js 20
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller --onefile --add-data "config.json:." --add-data "credentials.json:." --hidden-import schedule --name Scraper main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4 # Update to v4
        with:
          name: Scraper-macOS
          path: dist/Scraper
